### ISSUE TITLE
Libssh Failed to import the required Python library (ansible-pylibssh)

### ISSUE THREAD

**Issue by Ondjultomte** [ansible/pylibssh#513]
Im trying to use libssh to connet to cisco ios and ios xe devices, but its not working

msg": "Failed to import the required Python library (ansible-pylibssh) on xx's Python /opt/homebrew/Cellar/ansible/7.6.0/libexec/bin/python3.11. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}

```

The full traceback is:
  File "/opt/homebrew/Cellar/ansible/7.6.0/libexec/lib/python3.11/site-packages/ansible_collections/ansible/netcommon/plugins/modules/cli_command.py", line 170, in main
    response = connection.get(**module.params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/7.6.0/libexec/lib/python3.11/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
fatal: [sw80]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "answer": null,
            "check_all": false,
            "command": "show version",
            "newline": true,
            "prompt": null,
            "sendonly": false
        }
    },
    "msg": "Failed to import the required Python library (ansible-pylibssh) on xx's Python /opt/homebrew/Cellar/ansible/7.6.0/libexec/bin/python3.11. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"
}
```

pip3 install ansible-pylibssh
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
Requirement already satisfied: ansible-pylibssh in /opt/homebrew/lib/python3.11/site-packages (1.1.0)
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /opt/homebrew/lib/python3.11/site-packages/six-1.16.0-py3.11.egg-info due to invalid metadata entry 'name'

ansible --version
ansible [core 2.14.6]
  config file = None
  configured module search path = ['/Users/xx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/7.6.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/xx/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin//ansible
  python version = 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/Cellar/ansible/7.6.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

Im using the test playbook from RH

https://www.ansible.com/blog/new-libssh-connection-plugin-for-ansible-network
```

- hosts: "changeme"
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: "changeme"
    ansible_password: "changeme"
    ansible_network_cli_ssh_type: libssh
  tasks:
  - name: run show version command
    ansible.netcommon.cli_command:
      command: show version

  - name: run show interface command
    ansible.netcommon.cli_command:
       command: show interfaces
```
